[StyleBackground]
ImageName=#@#\Images\border.png
ScaleMargins=2,2,2,2
SolidColor=15,15,15,120
ImageTint=50,50,50
Padding=5,5,5,5
W=#width#
H=152

[StyleLogo]
ImageName=#@#\Images\f1.png
PreserveAspectRatio=1
W=35
Y=10
X=10

[StyleText]
AntiAlias=1
FontSize=10.5
FontFace=Roboto
FontColor=240,240,240
ClipString=1

[StyleTitle]
StringAlign=Center
X=(#width# / 2)
Y=5

[StyleSeperator]
SolidColor=255,255,255,25
X=#padding#
W=(#width# - (#padding# * 2))
H=1

[StyleNextRace]
StringAlign=Left
X=#padding#
Y=32

[StyleNext]
ImageName=#@#\Images\arrow-right.png
ImageTint=255,255,255,15
SolidColor=255,255,255,1
W=12
H=13
X=190
Y=35

[StylePrev]
ImageName=#@#\Images\arrow-left.png
ImageTint=255,255,255,15
SolidColor=255,255,255,1
W=12
H=13
X=180
Y=35

[StyleHeadings]
StringAlign=Right
X=(#width# - #padding#)
Y=32

[StyleEvents]
X=(#padding# * 4)
Y=58

[StyleTimes]
StringAlign=Right
X=(#width# - #padding#)
Y=58