; Calendar Styles

[StyleIcon]
ImageName=#@#\Images\f1.png
PreserveAspectRatio=1

[StyleBackground]
ImageName=#@#\Images\border.png
ScaleMargins=2,2,2,2
SolidColor=15,15,15,120
ImageTint=50,50,50
Padding=5,5,5,5
W=#width#
H=152

[StyleLogo]
ImageName=#@#\Images\f1.png
PreserveAspectRatio=1
W=35
Y=12
X=10

[StyleMinimize]
ImageName=#@#\Images\minimize.png
PreserveAspectRatio=1
ImageTint=255,255,255,15
SolidColor=255,255,255,1
W=20
Y=12
X=(#width# - 20)

[StyleSettings]
ImageName=#@#\Images\settings.png
PreserveAspectRatio=1
ImageTint=255,255,255,15
SolidColor=255,255,255,1
W=12
Y=11
X=(#width# - 35)


[StyleText]
AntiAlias=1
FontSize=10.5
FontFace=Roboto
FontColor=240,240,240
ClipString=1

[StyleTitle]
StringAlign=Center
X=(#width# / 2)
Y=7

[StyleSeperator]
SolidColor=255,255,255,25
X=#padding#
W=(#width# - #padding#)
H=1

[StyleNextRace]
StringAlign=Left
X=#padding#
Y=32

[StyleNext]
ImageName=#@#\Images\arrow-right.png
ImageTint=255,255,255,15
SolidColor=255,255,255,1
W=12
H=13
X=22
Y=61

[StylePrev]
ImageName=#@#\Images\arrow-left.png
ImageTint=255,255,255,15
SolidColor=255,255,255,1
W=12
H=13
X=10
Y=61

[StyleHeadings]
StringAlign=Right
X=(#width# - #padding#)
Y=32

[StyleEvents]
X=(#padding# * 4)
Y=58

[StyleTimes]
StringAlign=Right
X=(#width# - #padding#)
Y=58

; Settings Styles

[StyleBackgroundSettings]
ImageName=#@#\Images\border.png
ScaleMargins=2,2,2,2
SolidColor=15,15,15,120
ImageTint=50,50,50
Padding=5,5,5,5
W=200
H=150
